<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit039d4e2d631a0c2b80dd1fd88e444e60
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
        'M' => 
        array (
            'Muhammedabsar\\PhpMailerMaster\\' => 30,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
        'Muhammedabsar\\PhpMailerMaster\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit039d4e2d631a0c2b80dd1fd88e444e60::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit039d4e2d631a0c2b80dd1fd88e444e60::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit039d4e2d631a0c2b80dd1fd88e444e60::$classMap;

        }, null, ClassLoader::class);
    }
}
